[auth]
REDIRECT_URI = "https://liz-intent-analyzer.streamlit.app/oauth2callback"
cookie_seecret = "fvjhbvj3k3jbkejbfkj33j343b"

[auth.google]
GOOGLE_CLIENT_ID = "1030728653402-osfok26hos0thgkn1v1hhdd4nqakp4sb.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
project_id =	"upheld-apricot-396913"
REDIRECT_URI = "https://liz-intent-analyzer.streamlit.app/oauth2callback"
TOKEN_URI = "https://oauth2.googleapis.com/token"
ALLOWED_DOMAIN = "seedtag.com"
